image: alexxlalex/yashka:latest
pipelines:
  default:
    - step:
        name: build
        script:
          - mkdir -p build && cd build
          - cmake ..
          - make
        artifacts:
          - build/main
          - build/runTests
    - step:
        name: test
        script:
          - build/runTests test