image: alexxlalex/yashka:latest
pipelines:
  default:
    - step:
        name: build
        script:
          - cmake ./src
          - ls
          - cmake --build .
        artifacts:
          - build/main
          - build/runTests
    - step:
        name: test
        script:
          - build/runTests test