image: alexxlalex/yashka:latest
pipelines:
  default:
    - step:
        name: build
        script:
          - cmake -DCMAKE_BUILD_TYPE=Release  -G "Unix Makefiles" -S ./src -B ./src/cmake-build-debug && cmake ./src && cmake --build .
        artifacts:
          - src/bin/main
          - src/bin/runTests
    - step:
        name: test
        script:
          - valgrind --leak-check=full -s  src/bin/runTests