image: alexxlalex/yashka:latest
pipelines:
  default:
    - step:
        name: build
        script:
          - cmake -DCMAKE_BUILD_TYPE=Debug  -G "Unix Makefiles" -S ./src -B ./src/cmake-build-debug
          - cmake --build .
        artifacts:
          - src/bin/main
          - src/bin/runTests
    - step:
        name: test
        script:
          - src/bin/runTests test