image: alexxlalex/yashka:latest
pipelines:
  default:
    - step:
        name: build
        script:
          - cmake ./src
          - ls
          - cmake --build .
        artifacts:
          - bin/main
          - bin/runTests
    - step:
        name: test
        script:
          - bin/runTests test