image: alexxlalex/yashka:latest
pipelines:
  default:
    - step:
        name: build
        script:
          - mkdir -p build && cd build
          - cmake ..
          - make
        artifacts:
          - build/main
          - build/runTests
    - step:
        name: test
        script:
<<<<<<< HEAD
          - build/runTests test
=======
          - cd build
          - ./runTests test
>>>>>>> c126c27 (YAS-12-add-application-template-class)
