image: alexxlalex/yashka:latest
pipelines:
  default:
    - step:
        name: build
        script:
          - mkdir -p build && cd build
          - cmake ..
          - make
    - step:
        name: test
        script:
          - ls
          - cd build
          - ./runTests test