name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alexxlalex/yashka:latest
    steps:
      - name: clone
        uses: actions/checkout@v1
      - name: add build folder
        run: mkdir -p build
      - name: build
        working-directory: ./build
        run: cmake -DDOCKER=on -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -S .. -B . && cmake --build .
      - name: test
        run: valgrind --leak-check=full -s build/bin/runTests test
      - name: run lint
        run: echo "$(cpplint --recursive --exclude=build/* --output=emacs . > analyze.txt 2> analyze.txt)"
      - name: show lint analyze
        run: echo "$(cat analyze.txt)"
      - name: benchmark tests
        run: build/bin/bench
