name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alexxlalex/yashka:latest
    steps:
      - name: clone
        uses: actions/checkout@v1
      - name: add env
        run: export PATH=$PATH:/usr/local/unixODBC/bin && echo $PATH
      - name: move to build folder
        run: mkdir -p build
      - name: debug
        working-directory: ./build
        run: ls ..
      - name: build
        working-directory: ./build
        run: cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ..
      - name: build2
        working-directory: ./build
        run: cmake --build .
      - name: test
        run: valgrind --leak-check=full -s src/bin/runTests test
      - name: run lint
        run: echo "$(cpplint --recursive --exclude=cmake-build-debug/* --exclude=src/cmake-build-debug/* --exclude=_deps/* --exclude=CMakeFiles/* --output=emacs . > analyze.txt 2> analyze.txt)"
      - name: show lint analyze
        run: echo "$(cat analyze.txt)"
      - name: benchmark tests
        run: src/bin/bench
