name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alexxlalex/yashka:latest
    steps:
      - name: clone
        uses: actions/checkout@v1
      - name: build
        run: cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -S ./src -B ./src/cmake-build-debug && cmake ./src && cmake --build .
      - name: test
        run: valgrind --leak-check=full -s src/bin/runTests test
